#!/bin/bash
# Complete IGVC Autonomous Navigation Launch Script
# Run each command in a SEPARATE terminal
# Works regardless of clone location - replace WORKSPACE with your path (e.g. ~/IGVC_2)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$SCRIPT_DIR"

echo "=========================================="
echo "IGVC Full Autonomous Navigation Stack"
echo "=========================================="
echo ""
echo "This script shows the commands to run in separate terminals."
echo "Open 3 terminals and run each command in order."
echo "Workspace: $WORKSPACE"
echo ""
echo "=========================================="
echo "TERMINAL 1: Gazebo Simulation"
echo "=========================================="
echo "cd $WORKSPACE && source setup_orange.sh"
echo "ros2 launch orange_gazebo orange_igvc_simple.launch.xml"
echo ""
echo "Wait for Gazebo to fully load, then proceed to Terminal 2."
echo ""
echo "=========================================="
echo "TERMINAL 2: Waypoint Navigation"
echo "=========================================="
echo "cd $WORKSPACE && source setup_orange.sh"
echo "ros2 launch waypoint_navigation waypoint_nav.launch.xml \\"
echo "  use_sim_time:=true \\"
echo "  waypoints_file:=$WORKSPACE/install/orange_gazebo/share/orange_gazebo/config/waypoints/igvc_waypoints.yaml \\"
echo "  world_frame:=odom \\"
echo "  tandem_scan:=/hokuyo_scan"
echo ""
echo "Or use the perception stack: ros2 launch orange_gazebo igvc_perception_full.launch.xml"
echo ""
echo "An xterm window will open showing navigation status."
echo "The robot should start moving autonomously!"
echo ""
echo "=========================================="
echo "TERMINAL 3: RViz2 Visualization (Optional)"
echo "=========================================="
echo "cd $WORKSPACE && source setup_orange.sh"
echo "ros2 launch orange_bringup rviz2.launch.xml"
echo ""
echo "=========================================="
echo "OPTIONAL: Manual Control (if needed)"
echo "=========================================="
echo "cd $WORKSPACE && source setup_orange.sh"
echo "ros2 launch orange_teleop teleop_keyboard.launch.xml"
echo ""
echo "=========================================="
echo "Monitoring Commands (run in any terminal)"
echo "=========================================="
echo "# Check robot velocity:"
echo "ros2 topic echo /cmd_vel"
echo ""
echo "# Check robot position:"
echo "ros2 topic echo /odom --field pose.pose.position"
echo ""
echo "# Check LiDAR data:"
echo "ros2 topic echo /hokuyo_scan --field ranges[0:10]"
echo ""
echo "# List all topics:"
echo "ros2 topic list"
echo ""
echo "=========================================="
echo "To STOP everything:"
echo "=========================================="
echo "Press Ctrl+C in each terminal"
echo "Then run: pkill -9 gzserver; pkill -9 gzclient"
echo ""
